---
- name: Unarchive
  unarchive:
    src: "{{ hs_vault_local_secret_dir }}/vault.zip"
    dest: "/usr/local/bin"

- name: Set permissions on vault binary
  file:
    path: "/usr/local/bin/vault"
    mode: 0750

- name: Render system service
  template:
    src: vault.service.j2
    dest: "/lib/systemd/system/vault.service"
    mode: 0644
