---
- name: Unarchive
  unarchive:
    src: "/tmp/vault-{{ hs_vault_version }}.zip"
    dest: "/usr/bin"

- name: Set permissions on vault binary
  file:
    path: "/usr/local/bin/vault"
    mode: 0750

- name: Render system service
  template:
    src: vault.service.j2
    dest: "/lib/systemd/system/vault.service"
    mode: 0644
  notify: Restart vault
