---
driver:
  name: docker
platforms:
  - name: molecule-mono
    groups:
      - hashistack
      - hashistack_sre
      - hashistack_cluster
      - hashistack_masters
      - hashistack_minions
    image: galaxie-clans-debian:12
    log: true
    dockerfile: ../platforms/Dockerfile-debian-12.j2
    hostname: molecule-mono
    privileged: true
    pre_build_image: false
    pull: false
    etc_hosts: "{'molecule-mono.molecule.localdomain':'172.30.0.10'}"
    networks:
      - name: molecule-mono
        ipv4_address: 172.30.0.10
    docker_networks:
      - name: molecule-mono
        ipam_config:
          - subnet: '172.30.0.0/24'
            gateway: '172.30.0.254'
    published_ports:
      - "127.0.0.1:8200:8200/tcp"
      - "127.0.0.1:8501:8501/tcp"
      - "127.0.0.1:4646:4646/tcp"
      - "127.0.0.1:22000:22/tcp"
provisioner:
  name: ansible
  playbooks:
    prepare: ../playbooks/prepare.yml
    converge: ../playbooks/converge.yml
    verify: ../playbooks/verify.yml
  ansible_args:
    - "-e=@${MOLECULE_SCENARIO_DIRECTORY}/../../playbooks/group_vars/all.yml"
    - "-e=@${MOLECULE_SCENARIO_DIRECTORY}/_vars.yml"
    - "--skip-tags=prepare-tf-providers"
verifier:
  name: ansible
dependency:
  name: galaxy

