---
- name: Copy terraform sources    # noqa risky-file-permissions
  copy:
    src: "{{ role_path }}/files/telemetry/"
    dest: "{{ hs_vault_terraform_work_dir }}/vault_addon_telemetry/"
  delegate_to: localhost
  become: false
  run_once: true

- name: "Do Terraform"
  community.general.terraform:
    project_path: "{{ hs_vault_terraform_work_dir }}/vault_addon_telemetry"
    state: "present"    # noqa args
    force_init: true
    provider_upgrade: "{{ hs_tf_provider_upgrade | default(true) }}"
    workspace: "{{ hs_vault_cluster_name }}"
    variables:
      vault_address: >-
        {{ hs_vault_external_url }}
      vault_ca_cert_file: >-
        {{ hs_vault_use_custom_ca | ternary(hs_vault_local_ca_cert, '') | default(omit, true) }}
      auth_backend_path: "{{ hs_vault_addon_auth_ldap_path }}"
      server_url: "{{ hs_vault_addon_auth_ldap_server_url }}"
      user_dn: "{{ hs_vault_addon_auth_ldap_user_dn }}"
      user_attr: "{{ hs_vault_addon_auth_ldap_user_attr }}"
      user_principal_domain: "{{ hs_vault_addon_auth_ldap_user_principal_domain }}"
      discover_dn: "{{ hs_vault_addon_auth_ldap_discover_dn }}"
      group_dn: "{{ hs_vault_addon_auth_ldap_group_dn }}"
      group_filter: "{{ hs_vault_addon_auth_ldap_group_filter }}"
      bind_dn: "{{ hs_vault_addon_auth_ldap_bind_dn }}"
      bind_pass: "{{ hs_vault_addon_auth_ldap_bind_pass }}"
  environment:
    VAULT_ADDR: "{{ hs_vault_external_url }}"
    VAULT_TOKEN: "{{ vault_init_content.root_token }}"
    TF_CLI_ARGS: ""
    TF_CLI_ARGS_init: ""
    TF_CLI_ARGS_plan: ""
    TF_CLI_ARGS_apply: ""
    TF_CLI_ARGS_destroy: ""
  register: tf_result
  delegate_to: localhost
  throttle: 1
  become: false
  when:
    - __hs_vault_is_first_master

