---
- name: Load Vault variables namespace
  import_role:
    name: vault__vars__

- name: Execute os-specific tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_tasks_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  tags: always

- name: Start master vault services
  systemd:
    state: started
    name: vault
    daemon_reload: true
    enabled: true
  when: __hs_vault_is_master

- name: Silence minion vault
  systemd:
    state: stopped
    name: vault
    daemon_reload: true
    enabled: false
  when: __hs_vault_is_minion

- name: In-place init-unseal
  include_tasks: _inplace_init_unseal.yml
  when:
    - hs_vault_unseal_method == 'in-place'
    - __hs_vault_is_master
  tags: unseal

- name: Configure Vault instance using terraform
  include_tasks: _tf_configure.yml
  when: hs_vault_enable_default_policies

- name: Configure Vault instance using terraform
  include_tasks: "{{ role_path }}/_{{ _current_conf_addon }}.yml"
  loop: "{{ hs_vault_enabled_conf_addons }}"
  loop_control:
    loop_var: _current_conf_addon

- name: Flush before leaving
  meta: flush_handlers
  tags: always
