---
hs_workspace: molecule
hs_parent_domain: localdomain
hs_workspace_root: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
glxclans_workspace: "{{ hs_workspace_root }}"

public_domain: "{{ hs_workspace }}.{{ hs_parent_domain }}"

collection_root: "{{ (playbook_dir + '/../../') | realpath }}"

current_ssh_user: root

dns_enable: false

hs_vault_use_custom_ca: true
hs_consul_use_custom_ca: true
hs_nomad_use_custom_ca: true

tf_action: apply

glxclans_rproxy_nginx_managed_sites:
  - hashistack
