---
- name: Init local configuration files for hashistack instanciation
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Deprecation warning
      debug:
        msg: "==> DEPRECATED, USE wescale.hashistack.init playbook instead"

