---
- name: Deploy nginx
  hosts: "hashistack_sre"
  become: true
  gather_facts: true

  vars:
    glxclans_rproxy_enable: true
    glxclans_rproxy_nginx_enable_sites: true
    glxclans_rproxy_nginx_enable_streams: true

  roles:
    - rtnp.galaxie_clans.rproxy
    - stage1_rproxy
