---
- name: "Write value to vault kv-v2"
  hosts: "hashistack_masters[0]"
  become: false
  gather_facts: false

  vars:
    hs_vault_mount: "kv-v2"
    hs_vault_key_path: "hs_demo/custom_kv"
    hs_vault_data:
      sample_field_1: "alpha"
      sample_field_2:
        - "orange"
        - "apple"

  tasks:
    - name: "Load vault role variables"
      import_role:
        name: "vault_vars"

    - name: "Debug (-v)"
      debug:
        var: hs_vault_external_url
        verbosity: 1

    - name: "Put value to vault"  # noqa: run-once[task]
      community.hashi_vault.vault_kv2_write:
        url: "{{ hs_vault_external_url }}"
        engine_mount_point: "{{ hs_vault_mount }}"
        path: "{{ hs_vault_key_path }}"
        data: "{{ hs_vault_data }}"
      delegate_to: localhost
      run_once: true

